### ISSUE TITLE
New request: customize private repository

### ISSUE THREAD

**Issue by gzOne2Free** [luksa/kubectl-plugins#11]
Hi,
I use this plugin in company environment, and I want to retrieve image from our local private image repository instead of docker hub.

Can you add a function that let user privide their own repository location?

**Comment by luksa** [comment]
Hi. Which plugin are you referring to? kubectl-ssh?

**Comment by gzOne2Free** [comment]
Hi @luksa 

Thanks for your response. Yes I mean ssh plugin. We need to use a customized version of busybox image(more utils), so that we need ability to change image repository.  :p

**Comment by luksa** [comment]
You can now set the `KUBECTL_SSH_IMAGE` environment variable to use a custom image:
```
export KUBECTL_SSH_IMAGE=docker.io/alpine
kubectl ssh node my-node
```

**Comment by gzOne2Free** [comment]
@luksa 

Thank you very much!
Do i need to upgrade new ssh plugin to achieve this solution?

**Comment by gzOne2Free** [comment]
Or sorry, I saw Updated README document, thanks again.
