### ISSUE TITLE
kubectl ssh doesn't pick the `--kubeconfig` option

### ISSUE THREAD

**Issue by TAnas0** [luksa/kubectl-plugins#2]
Using `kubectl ssh node <node-name> --kubeconfig my-file.yaml` will not work on the K8s cluster of the configuration file

@luksa Is this something we want to support? What about the rest of the `kubectl` options? What about the rest of the commands?
I am not proficient in BASH programming but would like to contribute this if seen as useful

**Comment by magmax** [comment]
As bypass, you can use:
```
KUBECONFIG=my-file.yaml kubectl ssh node <node-name>
```

**Comment by mwoodpatrick** [comment]
I tried using this with a k3d cluster 

KUBECONFIG=$KUBECONFIG  kubectl ssh node k3d-westie-cluster-server-0

But it appeared to create a pod and ssh into that

Created pod/ssh-node-7qckk
Waiting for container to start...
If you don't see a command prompt, try pressing enter.

**Comment by luksa** [comment]
Both the `--kubeconfig` issue and the issue reported by @mwoodpatrick, where the plugin connects to the pod instead of the node, should now be fixed.

Thanks.

**Comment by mwoodpatrick** [comment]
Confirmed fixed. many thanks

**Comment by mwoodpatrick** [comment]
I tried to access the traefik node but that failed

kubectl ssh node traefik-66c46d954f-lk58h -n kube-system
Created pod/ssh-node-9dn4w
Waiting for container to start...
error: timed out waiting for the condition on pods/ssh-node-9dn4w
Error from server (NotFound): pods "ssh-node-9dn4w" not found
